id: PCBCBB45F
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA3JT13377
  instance_id: http://purl.bdrc.io/resource/IE3JT13377
  collection_id: http://purl.bdrc.io/resource/PR0ET010
  language_id: None
  title:
    bo:
    - མ་ཡི་དྲིན་ལན་བཤགས་མདོ་དང་། སྡོམ་པ་ཉེར་ལྔ་པ། བླང་དོར་བཞི་བཅུ་ཞེ་གཉིས་བཅས།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P1432
  publisher: Various
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    72f8cfb68fc54c6d9859b5bb9ca85b44:
      title: ༄༅།་།སྤྱི་ལོ་༢༠༠༦ཟླ་༡ཚེས་༧ནས་༡༤བར་གནས་མཆོག་རྡོ་རྗེ་གདན་དུ་དཔལ་རྒྱལ་དབང་༧ཀརྨ་པ་ཨོ་རྒྱན་འགྲོ་འདུལ་ཕྲིན་ལས་རྡོ་རྗེ་དབུ་བཞུགས་ཐོག་བ
      volume_number: 1
      base_file: UT3JT13377_001_0001.txt
      reference: http://purl.bdrc.io/resource/VLBEA7289AE94F57CC
      image_group: null
      quality: null
  reproductionOf: []
created_at: '2021-12-31T08:21:16.033579'
last_modified_at: '2021-12-31T08:21:16.033585'
statistics:
  total_words: 2852
  total_non_words: 386
quality:
  non_words_ratio: 0.14
